virtualenv:
  system_site_packages: true
before_install: sudo apt-get install libfreetype6 libfreetype6-dev imagemagick libmagickcore-dev libmagickwand-dev
language: ruby
script: "bundle exec rspec"
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode